### ISSUE TITLE
Allow controlling the order in which `dependencyManagement` BOM imports are rendered in the BOMs we generate

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-build#287]
While investigating https://github.com/micronaut-projects/micronaut-core/issues/7036, we realised the problem was because of the following BOM import chain:

```
micronaut-bom > micronaut-azure-bom > azure-sdk-bom > netty-bom
```

Note that also:

```
micronaut-bom > netty-bom
```

However, the `micronaut-azure-bom` import appears first, and it takes precedence over the `netty-bom` import.

While it is true that we should not have allowed `micronaut-azure-bom` to transitively bring `netty-bom` (which is what #286 requests), it is also true that third-party library BOMs used by micronaut-core (such as Netty, Groovy, etc) must be declared before any Micronaut module BOM.

**Comment by melix** [comment]
We don't have control over how this is written by Gradle. Libraries are written because they are `dependency` of a platform, but BOMs are on `dependencyConstraints`. There is no way to alter the order because those live into different containers and are therefore written in order, but separately. At the same time, we should avoid at all costs having something which is order dependent. This [PR](https://github.com/micronaut-projects/micronaut-build/pull/288) reworks validation to cover more cases.

**Comment by alvarosanchez** [comment]
I agree we shouldn't rely on ordering, however, it matters in Maven.

That said, if you say this can't be done, then let's close this issue.

**Comment by melix** [comment]
Yes I know it matters on Maven, unfortunately. There should be a way to reorder the POM by post-processing/rewriting it, but it's not great/easy to do.
