### ISSUE TITLE
Add java distribution as a cache input

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-build#494]
We have an action that builds core with Corretto, however, everything comes from the cache, as it was all built previously by the Temurin JDK

https://ge.micronaut.io/s/ygnvluei26hzc/timeline?details=7sbiibq2qxg2s&task-path=test

I asked in the [Gradle Slack](https://gradle.slack.com/archives/C02E00ZQTFV/p1676643618486449), and:

> We decided a while ago that for Java, caching based on the major version was good enough for most cases.
> If your use case requires more fine grained caching, you will need to leverage the inputs API to tell Gradle what to track.

To get the tests to run on the Corretto action, we should add an input to our compilation tasks that changes based on distribution so that the classes are compiled, and the tests are executed

**Comment by timyates** [comment]
One option would be to use toolchains, as then

> Are you using toolchains? If you do and you’d request a certain vendor for the test task then this vendor will also become an input. So when using toolchains all the requested fields will become an input, not only the Java major version.

But we probably don't want to do that

**Comment by timyates** [comment]
Or would adding

```
tasks.withType(AbstractCompile).configureEach {
    it.inputs.property("jdkDistribution", System.properties["java.vendor"])
}
```

to [`io.micronaut.build.internal.convention-base.gradle`](https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle) work as an alternative?

**Comment by melix** [comment]
This PR looks a bit suspicious to me. Eventually, we want to move to toolchain support, clearly. There should be no difference in compilation between Corretto, Oracle JDK or Temurin, so to me the fact that it fetches from cache is legit. You _may_ want to run _tests_ differently, but IMO only if you have a strong suspicion that it behaves differently at runtime. Is it the case?

**Comment by sdelamo** [comment]
can we not add test --rerun-tasks ?

**Comment by melix** [comment]
My question remains: what problem are you trying to solve?

**Comment by sdelamo** [comment]
We are trying to do what we said we were doing. https://micronaut.io/2020/04/09/micronaut-is-now-certified-to-run-on-amazon-corretto/ 

We stop building with Corretto accidentally.

**Comment by melix** [comment]
Site seems to be down. I can only imagine from the title that it's about making sure the test suite passes on Corretto. I would argue that it's a bit of wasted energy, because if tests pass on OpenJDK, they should pass on Corretto. But, if we want to make sure, then we have 2 options:

1. add the distribution as a property to test tasks (and not compile tasks, this really makes no sense since the user wouldn't build Micronaut on Corretto, they would use whatever distribution we provide, we want to test the runtime)
2. switch to using toolchains, which is still in the plans, but I still haven't got a good solution to the infamous GraalVM problem. This also requires changing our workflows.

The side effect is of course that depending on the JDK we all use, we will get cache misses.

**Comment by sdelamo** [comment]
@timyates can you do number 1? 

I think number 2 is a medium to long term solution. 

Corretto only runs on push 

https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/.github/workflows/corretto.yml#L3

**Comment by melix** [comment]
I will create a PR for 1, it's a simple change. Is it ok to target only 6.3.0?

**Comment by melix** [comment]
(note that the change will have to be reverted when we switch to toolchains, since the vendor version would be the one from the build running Gradle, not the one running tests)

**Comment by timyates** [comment]
Could we enable this via a system property?  Then we could just run the tests again in the corretto CI, and not locally because we probably all use different JDKs locally?

**Comment by melix** [comment]
Both are possible. If we run with `--no-build-cache` it will effectively work, but we will consume more CPU time than we need, and increase our feedback times, so I'm not super fan of it.

If I make `java.vendor` an input to the test task, then it fixes the problem, but anyone using a different JDK than the one on CI will not benefit from caching of tests anymore.

Making this configurable, so that only the Corretto build has this input is also possible, but then it requires setting this property in the workflow.
